# Generated by Django 5.1.1 on 2024-10-04 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('is_company', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('creditCard', 'Credit/Debit Card'), ('paypal', 'PayPal')], max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('subscription_type', models.CharField(choices=[('free', 'Free Tier'), ('monthly', 'Monthly Subscription'), ('yearly', 'Yearly Subscription')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
