# Generated by Django 5.1.1 on 2024-10-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0003_remove_optimizationdata_analysis_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('optimization_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualization', to='optimization.optimizationdata')),
            ],
        ),
    ]
